version: '3'

services:
  cogserver:
    # See https://github.com/developmentseed/titiler/discussions/387
    #platform: linux/amd64
    # enable `image` if you would like to use Docker image from Github package
    # image: ghcr.io/undp-data/titiler-aks:v0.0.2
    # enable `build` if you would like to build Docker image from source code
    build:
      context: .

    # Enable the following volumes if you want to mount source code to Docker
    # volumes:
      # - "./app/wmts.py:/opt/wmts/wmts.py"
    env_file:
      - gdal_rio.env
    ports:
      - 8000:80
#    environment:
#      # Application
#      - HOST=0.0.0.0
#      - PORT=8000


